### ISSUE TITLE
how 2 start?

### ISSUE THREAD

**Issue by reinfrcd** [ReZeroE/Amiya#4]
![image](https://github.com/ReZeroE/Amiya/assets/167173617/85468e50-f88e-4dfa-92a4-64a7750b1969)

**Comment by hcommak** [comment]
edited constants.py
![image](https://github.com/ReZeroE/Amiya/assets/167173617/0a8aaeff-355d-44a0-b0f6-740423869fd2)
![image](https://github.com/ReZeroE/Amiya/assets/167173617/bb6e46a8-2ffa-4cf6-a72b-2d6a40dbd858)

Fixed :)

**Comment by hcommak** [comment]
![image](https://github.com/ReZeroE/Amiya/assets/167173617/f2a3ff61-8fed-443a-a189-c2793a6edee7)
![image](https://github.com/ReZeroE/Amiya/assets/167173617/dc4078d4-da6f-4de9-8cfd-ee562d71c437)

are these just unimplemented or smth

**Comment by ReZeroE** [comment]
***
Thanks for reporting. All the commands listed with `help` are implemented.
***
I updated the module to v0.0.4 on PyPI and fixed the bugs you've encountered above. If you reinstall the module in v0.0.4, all the issues should be resolved:
```
$ pip uninstall amiya -y 
$ pip install amiya==0.0.4
```
Once the installation is completed, run
```
$ amiya
```
And then follow this to add an application:

![image](https://github.com/ReZeroE/Amiya/assets/68928036/654d0762-43a3-4581-862a-4114c9aca7f6)

Quotes around the path don't matter. Not including the quotes will work as well.
***
To list all the apps added, run `show-apps`.

![image](https://github.com/ReZeroE/Amiya/assets/68928036/e9cb7bfb-dbc6-4114-872c-4fe09e795717)
***

To delete an app that you don't want, run `remove-app`:

![image](https://github.com/ReZeroE/Amiya/assets/68928036/0a8f660e-543b-47e5-a31a-dfe9f834cda9)

***
Unfortunately, the module is still in development so there will be bugs here and there. I'll add some documentation for this module sometime soon.

**Comment by hcommak** [comment]
very nice, thx

btw, how 2 save recording?
![image](https://github.com/ReZeroE/Amiya/assets/167173617/407df1d0-6052-4370-b0fa-2dfdabd84dbc)
i saw tkinter in the automation recorder but no gui shows up

**Comment by hcommak** [comment]
![image](https://github.com/ReZeroE/Amiya/assets/167173617/1c9fb865-d6f4-451b-92c0-afd899302f0e)
tried to not touch anything and got this even if the app launches

**Comment by ReZeroE** [comment]
That's strange. When running `record-auto`, the application should first start and then prompt you that the recording has started.
However, it seems that the module stopped after it tried to start the application. 

Can you show me the output of running
```
$ amiya dev --isadmin
```
and then
```
$ amiya record-auto
```

I'll also leave some simple doc for these commands below.

***
***
To record an automation "sequence" of actions, run:
```
$ record-auto 
```
Then follow the promoted steps to start a recording. Once the recording starts, a small window on the screen should pop up, indicating that the recording has started.

The recording will capture key clicks and mouse clicks. I'm still working on capturing a combination of multiple keys so only single clicks are supported at the moment

Once you are ready to stop the recording, click the "stop recording" button on the pop-up window. It will automatically save the recording.

***

To run the recording, run:
```
$ run-auto <sequence_name>
```
The optional arguments can be pulled up using `run-auto --help`. Those options are sometimes useful.

The module is smart enough to identify the application's window and ensure that the application is always focused during the run (or else it would stop automatically to ensure it's running on a different application). 

The window size of the application also doesn't matter. It's capable of calculating the position of the mouse clicks even if the size of the window changes. 

***

About the error where the app starts but shows that the application failed to start, I'll take a look at that today. 

Right now, the module has a timeout of 30 seconds to check if the app started successfully. If the app's process doesn't initialize in that timeframe, it'll think that the app didn't start successfully.

**Comment by ReZeroE** [comment]
Also, if you have discord, I can add you there to help more efficiently.

**Comment by hcommak** [comment]
my discord is `hcommak`, ill record some tests in a few hrs

**Comment by ReZeroE** [comment]
Sorry, just saw your message over discord and replied to you there. Let me know if you need any other help or have any other suggestions. 

I'm currently working on ver0.0.5 so if there's anything you'd like me to add, I'm more than happy to push them out in this upcoming version.
